# To create a conda environment for this module:
# conda env create -f environment.yml
name: nibscbioinformatics-modules-cnvkit
# TODO change here the name of software only
channels:
  - conda-forge
  - bioconda
  - defaults
# TODO add any channels if and only if required to install the software
dependencies:
  - cnvkit=0.9.7
# TODO unless this is a multi software module, this should be only one
