# To create a conda environment for this module:
# conda env create -f environment.yml
name: nibscbioinformatics-modules-fastqc
# TODO change here the name of software only
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - nextflow=20.04.1
# WARNING no software to be installed a this time so we just put nextflow
