name: SAMPLEREADING
description: Run FastQC on sequenced reads
keywords:
  - Sample Processing
  - Parsing
params:
  - out_dir:
      type: string
      description: |
        The pipeline's output directory. By default, the module will
        output files into `$out_dir/MODULE_NAME`
  - publish_dir:
      type: string
      description: |
        Specifying this parameters, appends the string to the path for
        the standard output directory provided by `$out_dir`.
      default: MODULE_NAME (see out_dir)
  - publish_dir_mode:
      type: string
      description: |
        Provide a value for the Nextflow `publishDir` mode parameter
        (e.g. copy, link, ...)
  - publish_results:
      type: string
      description: |
        Whether or not to publish results into `publish_dir`. Set to `none` to not
        publish any files at all; to `default` to publish all relevant files.
      default: set to 'default', i.e. publishes all relevant files.
  - single_end:
    type: boolean
    description: |
      Boolean indicating whether the corresponding sample is single-end (true)
      or paired-end (false).
    default: false
input:
  - samplesheet:
      type: file
      description: |
        Sample sheet containing information about sample identifier and other columns,
        and including path (one per column) of the forward and reverse reads.
output:
  - sampledata:
      type: tuple
      description: Sample sheet containing 2 structures: a map [:] with sample metadata
        and an array [,] containing the path(s) to the read file(s).
