name: FastQC
description: Run FastQC on sequenced reads
keywords:
  - Quality Control
  - QC
tools:
  - fastqc:
      description: |
        FastQC produces a complete reports with metrics on your sequencing reads
        that help assessing the quality of your sequences and identify potential
        problems with the data. In particular, base quality, GC content as well as
        duplication levels and overrepresented sequences will help identifying how
        to inform any following step (for example, trimming).
      homepage: https://www.bioinformatics.babraham.ac.uk/projects/fastqc/
      documentation: https://www.bioinformatics.babraham.ac.uk/projects/fastqc/Help/
params:
  - params.modules['fastqc'].args:
      type: string
      description: Additional command line arguments passed to fastqc
        these are expected to be defined in a structured format under params.modules{}
        in the nextflow.config file
  - out_dir:
      type: string
      description: |
        The pipeline's output directory. By default, the module will
        output files into `$out_dir/MODULE_NAME`
  - publish_dir:
      type: string
      description: |
        Specifying this parameters, appends the string to the path for
        the standard output directory provided by `$out_dir`.
      default: MODULE_NAME (see out_dir)
  - publish_dir_mode:
      type: string
      description: |
        Provide a value for the Nextflow `publishDir` mode parameter
        (e.g. copy, link, ...)
  - publish_results:
      type: string
      description: |
        Whether or not to publish results into `publish_dir`. Set to `none` to not
        publish any files at all; to `default` to publish all relevant files.
      default: set to 'default', i.e. publishes all relevant files.
  - single_end:
    type: boolean
    description: |
      Boolean indicating whether the corresponding sample is single-end (true)
      or paired-end (false).
    default: false
input:
  - meta:
      type: map
      description: |
        The value is passed in a tuple, with the reads.
        This is a groovy map containing sample metadata which is
        generated in the main script. The following fields are expected
        by the module:
      - sampleID:
        type: string
        description: Sample identifier
  - reads:
      type: file
      description: |
        The list is passed in a tuple with the sample metadata (meta).
        List of input FastQ files of size 1 and 2 for single-end and paired-end data,
        respectively.
output:
  - html:
      type: tuple
      description: Metadata map (meta) together with FastQC report (type: file)
      pattern: "*_fastqc.html"
  - zip:
      type: tuple
      description: Metadata map (meta) together with FastQC report (type: file)
      pattern: "*_fastqc.zip"
  - version:
      type: file
      description: software version
      pattern: "*.version.txt"
