# To create a conda environment for this module:
# conda env create -f environment.yml
name: nibscbioinformatics-modules-flash
channels:
  - bioconda
  - defaults
dependencies:
  - flash==1.2.11--hed695b0_5
