name: cutadapt
description: Run cutadapt on sequenced reads
keywords:
  - Quality Control
  - QC
tools:
  - fastqc:
      description: |
        Cutadapt finds and removes adapter sequences, primers,
        poly-A tails and other types of unwanted sequence from
        high-throughput sequencing reads. It also trims the reads base
        on quality thresholds or desired length.
      homepage: https://pypi.org/project/cutadapt/
      documentation: https://cutadapt.readthedocs.io/en/stable/index.html
params:
  - params.modules['cutadapt'].adapterfile5:
      type: string
      description: file containing adapter sequences
        to be removed from the 5 prime side of the reads
  - params.modules['cutadapt'].adapterfile3:
      type: string
      description: file containing adapter sequences
        to be removed from the 3 prime side of the reads
  - outdir:
      type: string
      description: |
        The pipeline's output directory. By default, the module will
        output files into `$out_dir/cutadapt`
  - publish_dir:
      type: string
      description: |
        Specifying this parameters, appends the string to the path for
        the standard output directory provided by `$out_dir`.
      default: MODULE_NAME (see out_dir)
  - publish_dir_mode:
      type: string
      description: |
        Provide a value for the Nextflow `publishDir` mode parameter
        (e.g. copy, link, ...)
  - publish_results:
      type: string
      description: |
        Whether or not to publish results into `publish_dir`. Set to `none` to not
        publish any files at all; to `default` to publish all relevant files.
      default: set to 'default', i.e. publishes all relevant files.
  - single_end:
    type: boolean
    description: |
      Boolean indicating whether the corresponding sample is single-end (true)
      or paired-end (false).
    default: false
input:
  - meta:
      type: map
      description: |
        The value is passed in a tuple, with the reads.
        This is a groovy map containing sample metadata which is
        generated in the main script. The following fields are expected
        by the module:
      - sampleID:
        type: string
        description: Sample identifier
  - reads:
      type: file
      description: |
        The list is passed in a tuple with the sample metadata (meta).
        List of input FastQ files of size 1 and 2 for single-end and paired-end data,
        respectively.
output:
  - reads:
      type: tuple
      description: Metadata map (meta) together with trimmed read(s) (type: file)
      pattern: "*_trimmed.fastq.gz"
  - logs:
      type: tuple
      description: Metadata map (meta) together with FastQC logs (type: file)
      pattern: "*_trim.out" | "*_trim.err"
  - version:
      type: file
      description: software version
      pattern: "*.version.txt"
