name: Build FLASH

on:
  push:
    # Publish `$default-branch` as Docker `latest` image.
    branches:
      - flash
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
  # TODO: Change variable to your image's name.
  REPOSITORY: modules
  SOFTWARE: flash

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  push:
    paths: # TODO --> modify "template" below to refer to your module and your new action
      - software/flash/Dockerfile
      - software/flash/environment.yml
      - .github/workflows/flash_build.yml
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build ./software/template --file Dockerfile --tag $SOFTWARE

      - name: Log into GitHub Container Registry
      # TODO: Create a PAT with `read:packages` and `write:packages` scopes and save it as an Actions secret `CR_PAT`
        run: echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image to GitHub Container Registry
        run: |
          REPO=ghcr.io/${{ github.repository_owner }}/$REPOSITORY

          echo REPOSITORY=$REPO
          echo SOFTWARE=$SOFTWARE

          docker tag $SOFTWARE $REPO:$SOFTWARE
          docker push $REPO:$SOFTWARE
