name: Build FLASH

on:
  push:
    # Publish `$default-branch` as Docker `latest` image.
    branches:
      - flash
      - master
    paths: # TODO --> modify "template" below to refer to your module and your new action
      - software/flash/Dockerfile
      - software/flash/environment.yml
      - .github/workflows/flash_build.yml

  # Run tests for any PRs.
  pull_request:

env:
  # TODO: Change variable to your image's name.
  REPOSITORY: modules
  SOFTWARE: flash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
          IMAGETAGGED=ghcr.io/nibscbioinformatics/$REPOSITORY:$SOFTWARE
          docker build --tag $IMAGETAGGED ./software/$SOFTWARE/.

      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ secrets.GITPACKAGE_USER }} --password-stdin

      - name: Push image to GitHub Container Registry
        run: |
          IMAGETAGGED=ghcr.io/nibscbioinformatics/$REPOSITORY:$SOFTWARE
          docker push $IMAGETAGGED
