name: Docker Build & Push - Finishing

on:
  push:
    paths:
      - software/template/Dockerfile
      - software/template/environment.yml
      - .github/workflows/template_build.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build and push to Github Docker
        env:
          user: ${{ secrets.GITPACKAGE_USER }}
          token: ${{ secrets.GITPACKAGE_TOKEN }}
        run: |
        docker login https://docker.pkg.github.com -u "$user" --password "$token"
        docker build -t docker.pkg.github.com/nibscbioinformatics/modules/template software/template/.
        docker push docker.pkg.github.com/nibscbioinformatics/modules/template
