name: Docker Build & Push

on:
  push:
    paths: # TODO --> modify "template" below to refer to your module and your new action
      - software/template/Dockerfile
      - software/template/environment.yml
      - .github/workflows/template_build.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build and Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: nibscbioinformatics/nf-modules
          tags: template-test # TODO -> change "template" with your module name and "test" with software version
          path: ./software/template # TODO --> change "template" with your module name
