name: Docker Build & Push - Finishing

on:
  push:
    paths:
      - software/template/Dockerfile
      - software/template/environment.yml
      - .github/workflows/template_build.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build and Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: nibscbioinformatics/modules/template
          path: ./software/template
          tag_with_ref: true
