name: Docker Build & Push

on:
  push:
    paths: # TODO --> modify "template" below to refer to your module and your new action
      - software/template/Dockerfile
      - software/template/environment.yml
      - .github/workflows/template_build.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build and Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: nibscbioinformatics/modules/template # TODO -> change "template" with your module name
          path: ./software/template # TODO --> change "template" with your module name
          tag_with_ref: true
