name: Docker Build & Push - Finishing

on:
  push:
    paths:
      - software/template/Dockerfile
      - software/template/environment.yml
      - .github/workflows/template_build.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build and push to Github Docker
        run: |
        docker login https://docker.pkg.github.com -u ${{ secrets.GITPACKAGE_USER }} --password ${{ secrets.GITPACKAGE_TOKEN }}
        tag=test=`cat software/template/Dockerfile software/template/environment.yml | sha256sum | cut -f 1 -d" "`
        docker build -t docker.pkg.github.com/nibscbioinformatics/modules/template:${tag} software/template/.
        docker push docker.pkg.github.com/nibscbioinformatics/modules/template:${tag}
